// swift-tools-version: 5.9
// GENERATED by scripts/make_playground.py — do not edit by hand.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "JARVIS",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "JARVIS",
            targets: ["AppModule"],
            bundleIdentifier: "com.jarvis.assistant",
            displayVersion: "0.1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "JARVIS listens only while you talk to it, so you can speak your requests."),
                .speechRecognition(purposeString: "JARVIS turns your speech into text, on this iPad when supported."),
                .calendars(purposeString: "JARVIS reads your calendar to answer questions and plan your day, and adds or changes events only after you confirm."),
                .reminders(purposeString: "JARVIS reads and creates reminders when you ask it to."),
                .contacts(purposeString: "JARVIS looks up the person you name so it can prepare a message or call for you to confirm."),
                .camera(purposeString: "JARVIS uses the camera only when you choose to take a photo or video."),
                .photoLibraryAdd(purposeString: "JARVIS can save media you export back to your library.")
            ],
            appCategory: .productivity
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
