#!/usr/bin/env python3
"""Generate JARVIS.swiftpm, a Swift Playgrounds app package, from the main sources.

Swift Playgrounds on iPad builds and runs this package directly, no Mac needed.
Everything (JarvisCore + the iPad app) is compiled as one module, so the
`import JarvisCore` lines are dropped. Do not edit JARVIS.swiftpm by hand;
edit Sources/ and App/, then run:  python3 scripts/make_playground.py
"""
import pathlib
import shutil
import zipfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "JARVIS.swiftpm"
DIST = ROOT / "dist" / "JARVIS-Playground.zip"

PACKAGE = '''// swift-tools-version: 5.9
// GENERATED by scripts/make_playground.py — do not edit by hand.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "JARVIS",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "JARVIS",
            targets: ["AppModule"],
            bundleIdentifier: "com.jarvis.assistant",
            displayVersion: "0.1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "JARVIS listens only while you talk to it, so you can speak your requests."),
                .speechRecognition(purposeString: "JARVIS turns your speech into text, on this iPad when supported."),
                .calendars(purposeString: "JARVIS reads your calendar to answer questions and plan your day, and adds or changes events only after you confirm."),
                .reminders(purposeString: "JARVIS reads and creates reminders when you ask it to."),
                .contacts(purposeString: "JARVIS looks up the person you name so it can prepare a message or call for you to confirm."),
                .camera(purposeString: "JARVIS uses the camera only when you choose to take a photo or video."),
                .photoLibraryAdd(purposeString: "JARVIS can save media you export back to your library.")
            ],
            appCategory: .productivity
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
'''


def copy_swift(src_dir: pathlib.Path, dest_dir: pathlib.Path) -> None:
    for path in sorted(src_dir.rglob("*.swift")):
        target = dest_dir / path.relative_to(src_dir)
        target.parent.mkdir(parents=True, exist_ok=True)
        lines = path.read_text().splitlines(keepends=True)
        lines = [line for line in lines if line.strip() != "import JarvisCore"]
        target.write_text("".join(lines))


def main() -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir()
    (OUT / "Package.swift").write_text(PACKAGE)
    copy_swift(ROOT / "Sources" / "JarvisCore", OUT / "Core")
    copy_swift(ROOT / "App", OUT / "App")
    shutil.copytree(ROOT / "App" / "Resources" / "Assets.xcassets", OUT / "Assets.xcassets")

    DIST.parent.mkdir(exist_ok=True)
    with zipfile.ZipFile(DIST, "w", zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(OUT.rglob("*")):
            if path.is_file():
                info = zipfile.ZipInfo(str(path.relative_to(ROOT)), date_time=(2026, 1, 1, 0, 0, 0))
                info.compress_type = zipfile.ZIP_DEFLATED
                archive.writestr(info, path.read_bytes())
    print(f"Wrote {OUT.relative_to(ROOT)} and {DIST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
